language: generic
sudo: required
services:
    - docker
before_install:
    - docker build -t michelesalvucci/docker-react -f Dockerfile.dev .
script:
    - docker run -e CI=true michelesalvucci/docker-react npm run test